version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=tiktok-clone
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgresql:
    driver: local
